/**
 * CSV Generator Utilities
 * Generates CSV files for statements and order history
 */


export const generateStatementCSV = async (order) => {
  const lines = [];
  
  lines.push('ARKAD MINES & MINERALS - ACCOUNT STATEMENT');
  lines.push(`Order Number: ${order.orderNumber}`);
  lines.push(`Statement Date: ${new Date().toLocaleDateString('en-GB')}`);
  lines.push(`Account Holder: ${order.buyer?.companyName || order.buyer?.name || 'N/A'}`);
  lines.push(`Email: ${order.buyer?.email || 'N/A'}`);
  lines.push('');
  
  lines.push('=== ORDER SUMMARY ===');
  lines.push(`Order Date,${new Date(order.createdAt).toLocaleDateString('en-GB')}`);
  lines.push(`Order Status,${order.status}`);
  lines.push(`Payment Status,${order.paymentStatus}`);
  lines.push('');
  
  lines.push('=== ORDER ITEMS ===');
  lines.push('Item Name,Quantity,Unit Price,Total Price');
  if (order.items && order.items.length > 0) {
    order.items.forEach(item => {
      const price = item.unitPrice || 0;
      const quantity = item.quantity || 0;
      const total = price * quantity;
      lines.push(`${item.stoneName || 'N/A'},${quantity},${price.toFixed(2)},${total.toFixed(2)}`);
    });
  }
  lines.push('');
  
  lines.push('=== FINANCIAL SUMMARY ===');
  const financials = order.financials || {};
  lines.push(`Subtotal,${(financials.subtotal || 0).toFixed(2)}`);
  lines.push(`Tax (${financials.taxPercentage || 0}%),${(financials.taxAmount || 0).toFixed(2)}`);
  lines.push(`Shipping,${(financials.shippingCost || 0).toFixed(2)}`);
  lines.push(`Discount,${(financials.discountAmount || 0).toFixed(2)}`);
  lines.push(`Grand Total,${(financials.grandTotal || 0).toFixed(2)}`);
  lines.push('');
  
  lines.push('=== PAYMENT SUMMARY ===');
  lines.push(`Total Paid,${(order.totalPaid || 0).toFixed(2)}`);
  lines.push(`Outstanding Balance,${(order.outstandingBalance || 0).toFixed(2)}`);
  lines.push('');
  
  if (order.paymentTimeline && order.paymentTimeline.length > 0) {
    lines.push('=== PAYMENT HISTORY ===');
    lines.push('Date,Action,Amount Paid,Notes');
    order.paymentTimeline.forEach(entry => {
      const date = new Date(entry.timestamp).toLocaleDateString('en-GB');
      const action = entry.action?.replace(/_/g, ' ') || 'N/A';
      const amount = entry.amountPaid ? entry.amountPaid.toFixed(2) : '0.00';
      const notes = entry.notes || '';
      lines.push(`${date},${action},${amount},"${notes}"`);
    });
    lines.push('');
  }
  
  lines.push('=== END OF STATEMENT ===');
  lines.push('Generated by ARKAD MINES & MINERALS');
  lines.push(`Generated on: ${new Date().toLocaleString('en-GB')}`);
  
  return lines.join('\n');
};

/**
 * Generate CSV for Order History
 */
export const generateOrderCSV = async (orders) => {
  const lines = [];
  
  lines.push('ARKAD MINES & MINERALS - ORDER HISTORY');
  lines.push(`Generated Date: ${new Date().toLocaleDateString('en-GB')}`);
  lines.push(`Total Orders: ${orders.length}`);
  lines.push('');
  
  lines.push('=== ORDERS ===');
  lines.push('Order Number,Date,Status,Payment Status,Subtotal,Tax,Shipping,Discount,Grand Total,Total Paid,Outstanding Balance');
  
  orders.forEach(order => {
    const financials = order.financials || {};
    const date = new Date(order.createdAt).toLocaleDateString('en-GB');
    lines.push([
      order.orderNumber || 'N/A',
      date,
      order.status || 'N/A',
      order.paymentStatus || 'N/A',
      (financials.subtotal || 0).toFixed(2),
      (financials.taxAmount || 0).toFixed(2),
      (financials.shippingCost || 0).toFixed(2),
      (financials.discountAmount || 0).toFixed(2),
      (financials.grandTotal || 0).toFixed(2),
      (order.totalPaid || 0).toFixed(2),
      (order.outstandingBalance || 0).toFixed(2)
    ].join(','));
  });
  
  lines.push('');
  lines.push('=== END OF REPORT ===');
  lines.push('Generated by ARKAD MINES & MINERALS');
  
  return lines.join('\n');
};
