FROM node:20-alpine
WORKDIR /workspace


COPY ["ARKAD_Mines admin/package.json", "ARKAD_Mines admin/package-lock.json", "./admin/"]
COPY shared/package.json ./shared/package.json

WORKDIR /workspace/admin
RUN npm install


COPY ["ARKAD_Mines admin/", "./"]
COPY shared/ ../shared/

ENV VITE_API_URL=http://80.225.198.154
RUN npm run build && npm install -g serve
EXPOSE 5174
CMD ["serve", "-s", "dist", "-l", "5174"]
